name: Build-Release Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
  workflow_dispatch:

env:
  PACKAGE_FILE: "bootscript"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
      - run: go build -o ${{ env.PACKAGE_FILE }}
      - uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: ${{ env.PACKAGE_FILE }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-package
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
      - run: gh release upload ${{ github.ref_name }} ${{ env.PACKAGE_FILE }}
