name: Build-Release Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
  workflow_dispatch:

env:
  PACKAGE_FILE: "bootscript"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
      - run: go build -o ${{ env.PACKAGE_FILE }}
      - uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: ${{ env.PACKAGE_FILE }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          name: built-package
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PACKAGE_FILE }}
