name: Pre-commit checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  precommit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
